In [2]:
import torch
## 1d vector with three elements
x=torch.empty(3)
## 2d matrix
y=torch.empty(2,4)
print(y)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([0., 0., 0.])


In [3]:
z=torch.ones(2,2)
print(z)

tensor([[1., 1.],
        [1., 1.]])


In [4]:
## declaring the datatype of variable
z=torch.ones(2,2,dtype=torch.int)
print(z)
print(z.size())

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.Size([2, 2])


In [5]:
x=torch.tensor([2.5,0.1])

In [6]:
print(x)

tensor([2.5000, 0.1000])


In [7]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.7479, 0.4130],
        [0.3880, 0.0706]])
tensor([[0.4418, 0.5248],
        [0.1300, 0.4452]])


In [8]:
z=x*y
print(z)

tensor([[0.3304, 0.2167],
        [0.0504, 0.0314]])


In [9]:
z=x+y
print(z)

tensor([[1.1897, 0.9377],
        [0.5180, 0.5158]])


In [10]:
x=torch.rand(4,4)
print(x)

tensor([[0.9229, 0.0080, 0.6285, 0.7519],
        [0.0997, 0.7468, 0.6146, 0.8320],
        [0.1801, 0.5341, 0.1860, 0.0144],
        [0.9418, 0.2476, 0.3641, 0.7074]])


In [12]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)
a.add_(1)
print(a)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
